production:
  sessions:
    default:
      hosts:
        - <%= ENV['MONGOLAB_HOSTS'] %>
      username: <%= ENV['MONGOLAB_USER'] %>
      password: <%= ENV['MONGOLAB_PASSWORD'] %>
      database: <%= ENV['MONGOLAB_DATABASE'] %>